spring:
  profiles:
    active: dev
  application:
    name: blog-web

  #thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5 #使用非严格意义的HTML5, 需要添加NekoHTML库
    encoding: UTF-8
    content-type: text/html
    cache: false

  # 静态资源策略
  resources:
    static-locations: classpath:/static/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

#Logging 配置
logging:
  path: /home/logs/blog-web/
  file: blog-web.log
  level:
    cn.newtouch.kiseki.web: INFO

server:
  port: 21080